platzigram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts import views

urlpatterns = [
    path('', views.PostsFeedView.as_view(), name='feed'),
    path('posts/new/', views.CreatePostView.as_view(), name='create_post'),
    path('posts/<int:pk>', views.PostDetail.as_view(), name='detail')
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [

    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
    ),

    # Posts
    path('<str:username>/',
         views.DetailView.as_view(),
         name='detail'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head_content %}{% endblock %}

    <link rel="stylesheet" href="{% static "css/main.css" %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />


</head>

<body>
    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}

        {% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static "jquery/js/jquery-3.3.1.slim.min.js" %}"></script>
    <script src="{% static "popper/js/popper.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>

</html>

templates/nav.html
{% load static %}


<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light" id="main-navbar">

    <div class="container">

        <!-- Logo -->
        <a class="navbar-brand pr-5" style="border-right:1px solid #efefef;" href="{% url 'posts:feed' %}">Platzigram <img src="{% static "img/instagram.png" %}" alt="" height="45" class="d-inline-block aling-top"></a>

        <!-- Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbargram" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Menú -->
        <div class="collapse navbar-collapse" id="navbargram">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="#">
                        {% if request.user.profile.picture %}
                        <a href="{% url 'users:detail' request.user.username %}">
                            <img src="{{request.user.profile.picture.url}}" alt="{{request.user.username}}" height="35" class="d-inline-block align-top rounded-circle">
                        </a>
                        {% else %}
                        <img src="{% static "img/default-profile.png" %}" alt="{{request.user.username}}" height="35" class="d-inline-block align-top rounded-circle">
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item nav-icon">
                    <a class="nav-link" href="{% url 'posts:create_post' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item nav-icon">
                    <a class="nav-link" href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
                {% endif %}

            </ul>
        </div>

    </div>

</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>