platzigram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts import views

urlpatterns = [
    path('', views.PostsFeedView.as_view(), name='feed'),
    path('posts/new/', views.CreatePostView.as_view(), name='create_post'),
    path('posts/<int:pk>', views.PostDetail.as_view(), name='detail')
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [

    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
    ),

    # Posts
    path('<str:username>/',
         views.DetailView.as_view(),
         name='detail'),

]

users/models.py
"""Users models"""

# Django
from django.db import models
from django.contrib.auth.models import User

# ██████  ██████   ██████  ███████ ██ ██      ███████
# ██   ██ ██   ██ ██    ██ ██      ██ ██      ██
# ██████  ██████  ██    ██ █████   ██ ██      █████
# ██      ██   ██ ██    ██ ██      ██ ██      ██
# ██      ██   ██  ██████  ██      ██ ███████ ███████

class Profile(models.Model):
    """Profile Model.
    Proxy model that extends the basedata with other information.
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )
    website = models.URLField(
        max_length=200,
        blank=True
    )
    biography = models.TextField(
        blank=True
    )
    phone_number = models.CharField(
        max_length=20,
        blank=True
    )
    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    modified = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        """Return username."""
        return self.user.username

users/forms.py
"""Users forms."""
from django import forms
from django.contrib.auth.models import User
from users.models import Profile

# ██████  ██████   ██████  ███████ ██ ██      ███████
# ██   ██ ██   ██ ██    ██ ██      ██ ██      ██
# ██████  ██████  ██    ██ █████   ██ ██      █████
# ██      ██   ██ ██    ██ ██      ██ ██      ██
# ██      ██   ██  ██████  ██      ██ ███████ ███████


class ProfileForm(forms.Form):
    """Profile form."""
    website = forms.URLField(max_length=200,
                             required=True,
                             widget=forms.URLInput(
                                 attrs={
                                     'class': 'form-control',
                                     'placeholder': 'Website'
                                 }))
    biography = forms.CharField(max_length=500,
                                required=False,
                                widget=forms.Textarea(
                                    attrs={
                                        'class': 'form-control',
                                        'placeholder': 'Biography',
                                        'rows': 3,
                                    }))
    phone_number = forms.CharField(max_length=20,
                                   required=False,
                                   widget=forms.TextInput(attrs={
                                       'class': 'form-control',
                                       'placeholder': 'Phone number'
                                   })
                                   )
    picture = forms.ImageField()


# ███████ ██ ███    ██  ██████      ██    ██ ██████
# ██      ██ ████   ██ ██           ██    ██ ██   ██
# ███████ ██ ██ ██  ██ ██   ███     ██    ██ ██████
#      ██ ██ ██  ██ ██ ██    ██     ██    ██ ██
# ███████ ██ ██   ████  ██████       ██████  ██

class SignupForm(forms.Form):
    username = forms.CharField(required=True,
                               min_length=4,
                               max_length=50,
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Username', }))
    password = forms.CharField(required=True,
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Password', }))
    password_confirmation = forms.CharField(required=True,
                                            widget=forms.PasswordInput(attrs={
                                                'class': 'form-control',
                                                'placeholder': 'Password confirmation', }))
    first_name = forms.CharField(required=True,
                                 min_length=4,
                                 max_length=50,
                                 widget=forms.TextInput(attrs={
                                     'class': 'form-control',
                                     'placeholder': 'First name', }))
    last_name = forms.CharField(required=True,
                                min_length=4,
                                max_length=50,
                                widget=forms.TextInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Last name', }))
    email = forms.EmailField(required=True,
                             min_length=6,
                             max_length=70,
                             widget=forms.EmailInput(attrs={
                                 'class': 'form-control',
                                 'placeholder': 'Email', }))

    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
"""Users views.AssertionError(args)"""

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, UpdateView
from posts.models import Post
from users.forms import SignupForm
from users.models import Profile, User

# ██       ██████   ██████  ██ ███    ██
# ██      ██    ██ ██       ██ ████   ██
# ██      ██    ██ ██   ███ ██ ██ ██  ██
# ██      ██    ██ ██    ██ ██ ██  ██ ██
# ███████  ██████   ██████  ██ ██   ████


class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['username'].widget.attrs.update({
            'class': 'form-control'})
        form.fields['password'].widget.attrs.update({
            'class': 'form-control'})
        return form

    def get(self, request, *args, **kwargs):
        """Handle GET requests: instantiate a blank version of the form."""
        if request.user.is_authenticated:
            return redirect('posts:feed')
        return super().get(request, args, kwargs)


# ██       ██████   ██████   ██████  ██    ██ ████████
# ██      ██    ██ ██       ██    ██ ██    ██    ██
# ██      ██    ██ ██   ███ ██    ██ ██    ██    ██
# ██      ██    ██ ██    ██ ██    ██ ██    ██    ██
# ███████  ██████   ██████   ██████   ██████     ██

class LogoutView(auth_views.LogoutView):
    """Logout a user."""
    next_page = reverse_lazy('users:login')


# ███████ ██ ███    ██  ██████  ██    ██ ██████
# ██      ██ ████   ██ ██       ██    ██ ██   ██
# ███████ ██ ██ ██  ██ ██   ███ ██    ██ ██████
#      ██ ██ ██  ██ ██ ██    ██ ██    ██ ██
# ███████ ██ ██   ████  ██████   ██████  ██

class SignupView(FormView):
    """Sign up view."""
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

# ██    ██ ██████  ██████   █████  ████████ ███████
# ██    ██ ██   ██ ██   ██ ██   ██    ██    ██
# ██    ██ ██████  ██   ██ ███████    ██    █████
# ██    ██ ██      ██   ██ ██   ██    ██    ██
#  ██████  ██      ██████  ██   ██    ██    ███████

# ██████  ██████   ██████  ███████ ██ ██      ███████
# ██   ██ ██   ██ ██    ██ ██      ██ ██      ██
# ██████  ██████  ██    ██ █████   ██ ██      █████
# ██      ██   ██ ██    ██ ██      ██ ██      ██
# ██      ██   ██  ██████  ██      ██ ███████ ███████


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile."""
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile"""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['website'].widget.attrs.update({
            'class': 'form-control'})
        form.fields['biography'].widget.attrs.update({
            'class': 'form-control',
            'rows': 3})
        form.fields['phone_number'].widget.attrs.update({
            'class': 'form-control'})
        return form


# ██████  ███████ ████████  █████  ██ ██
# ██   ██ ██         ██    ██   ██ ██ ██
# ██   ██ █████      ██    ███████ ██ ██
# ██   ██ ██         ██    ██   ██ ██ ██
# ██████  ███████    ██    ██   ██ ██ ███████

# ██    ██ ██ ███████ ██     ██
# ██    ██ ██ ██      ██     ██
# ██    ██ ██ █████   ██  █  ██
#  ██  ██  ██ ██      ██ ███ ██
#   ████   ██ ███████  ███ ███


class DetailView(LoginRequiredMixin, DetailView):
    """Detail user data"""
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    context_object_name = 'user'
    model = User
    queryset = User.objects.all()

    def get_context_data(self, **kwargs):
        """Add user's posts to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head_content %}{% endblock %}

    <link rel="stylesheet" href="{% static "css/main.css" %}">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />

</head>

<body>

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <img src="{% static "img/instagram.png" %}" alt="" class="img-fluid rounded mx-auto d-block pb-4" style="max-width:60%;">
                {% block container %}

                {% endblock %}
            </div>
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static "jquery/js/jquery-3.3.1.slim.min.js" %}"></script>
    <script src="{% static "popper/js/popper.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>

</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>Account</title>
{% endblock %}

{% block container %}
<div class="container mb-5" style="margin-top: 8em;">
    <div class="row">
        <div class="col-sm-4 d-flex justify-content-center">
            <img src="{{user.profile.picture.url}}" alt="@{{user.username}}" class="rounded-circle" style="max-height: 150px;">
        </div>
        <div class="col-sm-8">
            <h2 style="font-weigth: 100;">
                {{user.username}}
                {% if user == user %}
                <a href="{% url 'users:update_profile' %}" class="ml-5 btn btn-sm btn-outline-info">Edit profile</a>
                {% else %}
                <a class="ml-5 btn btn-sm btn-primary">Follow</a>
                {% endif %}
            </h2>
            <div class="row mt-2" style="font-size: 1.2em">
                <div class="col-sm-4">
                    <b>{{user.profile.post_count}}785</b> posts
                </div>
                <div class="col-sm-4">
                    <b>{{user.profile.followers}}1,401</b> followers
                </div>
                <div class="col-sm-4">
                    <b>{{user.profile.following}}491</b> following
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-sm-12">
                    <p>
                        {{user.profile.biography}}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>

<div class="container" id="user-posts">
    <div class="row mt-3">
        {% for post in posts %}
        <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex jusify-content-center align-items-center">
            <a href="{% url 'posts:detail' post.pk %}" class="border">
                <img src="{{post.photo.url}}" alt="{{post.title}}" class="img-fluid">
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}
{% block head_content %}
<title>Login</title>
{% endblock %}

{% block container %}
<div class="row">
    <div class="col">
        <form action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary btn-block mt-5">Sing in!</button>

        </form>
    </div>
</div>
<p class="mt-4">
    Don't have an account yet?
    <a href="{% url 'users:signup' %}">Sign up here</a>
</p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Sing Up</title>
{% endblock %}

{% block container %}
<div class="row">
    <div class="col">

        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
        {% endif %}

        <form action="{% url 'users:signup' %}" method="POST">
            {% csrf_token %}

            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                <small>{{ error }}</small>
            </div>
            {% endfor %}
            {% endif %}

            {% for field in form %}
            <div class="fieldWrapper form-group" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                <!--{{ field.label_tag }}{% if field.field.required %}<span class="required" style="color: red;">*</span>{% endif %}-->
                {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
                {% if field.errors %}
                {% for error in field.errors %}
                <small class="mt-0 text-danger">
                    {{error | escape}}
                </small>
                {% endfor %}
                {% endif %}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary btn-block">Sign in</button>
        </form>
    </div>
</div>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{request.user.username}} | Update profile</title>
{% endblock %}

{% block container %}
<div class="row justify-content-md-center">
    <div class="col-6 p-4" id="profile-box">

        <!--
███████  ██████  ██████  ███    ███
██      ██    ██ ██   ██ ████  ████
█████   ██    ██ ██████  ██ ████ ██
██      ██    ██ ██   ██ ██  ██  ██
██       ██████  ██   ██ ██      ██
-->

        <form action="{% url 'users:update_profile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="media">
                <img src="{% if not profile.picture %}{% static "img/default-profile.png" %}{% else %}{{profile.picture.url}}{% endif %}" alt="{{user.username}}" class="rounded-circle" height="50">
                <div class="media-body">
                    <h5 class="ml-4">
                        @{{user.username}} | {{user.get_full_name}}
                    </h5>
                </div>
            </div>
            <!--<p class="ml-4 mt-2" style="font-size: 0.8em">
                    {{form.picture}}
                </p>-->

            <hr><br>

            {% for field in form %}
            <div class="fieldWrapper form-group" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                {{ field.label_tag }}{% if field.field.required %}<span class="required" style="color: red;">*</span>{% endif %}
                {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
                {% if field.errors %}
                <small class="mt-0 text-danger">
                    {{field.errors}}
                </small>
                {% endif %}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary btn-block btn-sm mt-5">Update info</button>
        </form>

        <!--
███████  ██████  ██████  ███    ███         ██
██      ██    ██ ██   ██ ████  ████        ██
█████   ██    ██ ██████  ██ ████ ██       ██
██      ██    ██ ██   ██ ██  ██  ██      ██
██       ██████  ██   ██ ██      ██     ██
-->

    </div>
</div>
{% endblock %}